spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
    hibernate:
      ddl-auto: validate
    database: postgresql

  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/token?user=tbsklg
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true